<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MagicSlideShow
 * @author    Webkul
 * @copyright Copyright (c) 2010-2017 Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<script>
    require([
        'jquery',
        'mage/adminhtml/grid',
        'prototype'
    ], function(jQuery){
        jQuery("#edit_form").append('<input type="hidden" id="image_ids" name="image_ids" value="" >');
        var checkBoxes = "<?php echo $this->getImagesIds() ?>";
        jQuery('#image_ids').val(checkBoxes);
        function setValues() {
            var ids = [];
            jQuery("table tbody tr td input:checkbox").each(function(){
                if(jQuery(this).prop("checked")) {
                    id = jQuery(this).val();
                    ids.push(id);
                }
            });
            ids.sort();
            ids = ids.join(',');
            jQuery("#image_ids").val(ids);
        }
        jQuery(document).ready(function(){
            jQuery(document).on('click', 'table tbody tr', function(event) {
                setValues();
            });
            jQuery(document).on('click', 'table tbody tr td', function(event) {
                setValues();
            });
            jQuery(document).on('click', 'table thead tr', function(event) {
                setValues();
            });
        });
    });
</script>