<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MagicSlideShow
 * @author    Webkul
 * @copyright Copyright (c) 2010-2017 Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

/**
 * MagicSlideShow sliderimages js Admin Template
 */
$helper = $this->helper('Webkul\MagicSlideShow\Helper\Data');
$allowedExtensions = $helper->getAllowedExtensions(true);
?>
<script>
    require([
        'jquery',
        'mage/adminhtml/grid',
        'prototype'
    ], function(jQuery) {
        jQuery(document).ready(function() {
            var allowedExtensions = [<?php echo implode(",",$allowedExtensions); ?>];
            if (jQuery(".delete-image").length) {
                // jQuery(".delete-image").remove();
            } else {
                // jQuery("#sliderimages_image").addClass("required-entry");
            }
            jQuery("#sliderimages_filename").on("change", function(){
                var fileName = jQuery(this).val();
                var ext = fileName.split('.').pop().toLowerCase();
                if(jQuery.inArray(ext, allowedExtensions) == -1) {
                    alert('Image type not allowed!');
                    jQuery(this).val('');
                }
            });
        });
    });
</script>